static class Shapes {
  static final int DEAD = Grid.DEAD;
  static final int ALIV = Grid.ALIVE;


  static int[][] GLIDER_GUN_SE = {
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV},
    {ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, ALIV, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD}};
  
  static int[][] GLIDER_GUN_SW = {
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, ALIV, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD},
    {DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, ALIV, ALIV, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD, DEAD}};

  static int[][] GLIDER_NW = {
    {ALIV, ALIV, ALIV},
    {ALIV, DEAD, DEAD},
    {DEAD, ALIV, DEAD}
  };

  static int[][] GLIDER_NE = {
    {ALIV, ALIV, ALIV},
    {DEAD, DEAD, ALIV},
    {DEAD, ALIV, DEAD}
  };

  static int[][] GLIDER_SW = {
    {DEAD, ALIV, DEAD},
    {ALIV, DEAD, DEAD},
    {ALIV, ALIV, ALIV}
  };

  static int[][] GLIDER_SE = {
    {DEAD, ALIV, DEAD},
    {DEAD, DEAD, ALIV},
    {ALIV, ALIV, ALIV}
  };
}
